# Generated by Django 5.1.7 on 2025-08-15 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente si se deja vacío', max_length=140, unique=True)),
                ('category', models.CharField(choices=[('sports', 'Deportiva'), ('crafts', 'Manualidades')], max_length=20, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Contenido')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publicado')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Destacado')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField(verbose_name='Inicio')),
                ('end_time', models.TimeField(verbose_name='Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.activity')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
